apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expandable-storage
provisioner: kubernetes.io/host-path
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate