apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: redis-operator-system
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Tag               redis.operator.*
        Path              /var/log/containers/*redis-operator*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [INPUT]
        Name              tail
        Tag               redis.instance.*
        Path              /var/log/containers/*redis*.log
        Exclude_Path      /var/log/containers/*redis-operator*.log
        Parser            docker
        DB                /var/log/flb_redis.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                kubernetes
        Match               redis.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     redis.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On

    [FILTER]
        Name                parser
        Match               redis.operator.*
        Key_Name            log
        Parser              redis_operator_parser
        Reserve_Data        On

    [FILTER]
        Name                parser
        Match               redis.instance.*
        Key_Name            log
        Parser              redis_instance_parser
        Reserve_Data        On

    [FILTER]
        Name                modify
        Match               redis.*
        Add                 cluster_name ${CLUSTER_NAME}
        Add                 environment ${ENVIRONMENT}

    [OUTPUT]
        Name            es
        Match           redis.operator.*
        Host            ${ELASTICSEARCH_HOST}
        Port            ${ELASTICSEARCH_PORT}
        Index           redis-operator-logs
        Type            _doc
        Logstash_Format On
        Logstash_Prefix redis-operator
        Logstash_DateFormat %Y.%m.%d
        Time_Key        @timestamp
        Time_Key_Format %Y-%m-%dT%H:%M:%S.%L%z
        Include_Tag_Key On
        Tag_Key         tag
        Retry_Limit     5
        Buffer_Size     32KB

    [OUTPUT]
        Name            es
        Match           redis.instance.*
        Host            ${ELASTICSEARCH_HOST}
        Port            ${ELASTICSEARCH_PORT}
        Index           redis-instance-logs
        Type            _doc
        Logstash_Format On
        Logstash_Prefix redis-instance
        Logstash_DateFormat %Y.%m.%d
        Time_Key        @timestamp
        Time_Key_Format %Y-%m-%dT%H:%M:%S.%L%z
        Include_Tag_Key On
        Tag_Key         tag
        Retry_Limit     5
        Buffer_Size     32KB

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On

    [PARSER]
        Name        redis_operator_parser
        Format      regex
        Regex       ^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)\s+(?<level>\w+)\s+(?<logger>[^\s]+)\s+(?<message>.*?)(?:\s+(?<fields>\{.*\}))?$
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On

    [PARSER]
        Name        redis_instance_parser
        Format      regex
        Regex       ^(?<pid>\d+):[A-Z]\s+(?<timestamp>\d{2}\s+\w{3}\s+\d{4}\s+\d{2}:\d{2}:\d{2}\.\d{3})\s+(?<level>[*#-])\s+(?<message>.*?)$
        Time_Key    timestamp
        Time_Format %d %b %Y %H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        redis_sentinel_parser
        Format      regex
        Regex       ^(?<pid>\d+):[A-Z]\s+(?<timestamp>\d{2}\s+\w{3}\s+\d{4}\s+\d{2}:\d{2}:\d{2}\.\d{3})\s+(?<level>[*#-])\s+(?<message>.*?)$
        Time_Key    timestamp
        Time_Format %d %b %Y %H:%M:%S.%L
        Time_Keep   On

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: redis-operator-system
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
        env:
        - name: FLUENT_CONF
          value: "/fluent-bit/etc/fluent-bit.conf"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.logging.svc.cluster.local"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: CLUSTER_NAME
          value: "redis-operator-cluster"
        - name: ENVIRONMENT
          value: "production"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 100Mi
            cpu: 50m
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: redis-operator-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - pods/logs
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: redis-operator-system

---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: redis-operator-system
  labels:
    app: fluent-bit
spec:
  ports:
  - port: 2020
    targetPort: 2020
    protocol: TCP
    name: http
  selector:
    app: fluent-bit