---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.github.com
  resources:
  - configs
  - redis
  - redisclusters
  - redisinstances
  - redismasterreplicas
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.github.com
  resources:
  - configs/finalizers
  - redis/finalizers
  - redisclusters/finalizers
  - redisinstances/finalizers
  - redismasterreplicas/finalizers
  - redissentinels/finalizers
  verbs:
  - update
- apiGroups:
  - redis.github.com
  resources:
  - configs/status
  - redis/status
  - redisclusters/status
  - redisinstances/status
  - redismasterreplicas/status
  - redissentinels/status
  verbs:
  - get
  - patch
  - update
