apiVersion: redis.github.com/v1
kind: RedisMasterReplica
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redismasterreplica-sample
spec:
  # TODO(user): Add fields here
