apiVersion: redis.github.com/v1
kind: RedisInstance
metadata:
  name: redisinstance-sample
  namespace: default
spec:
  replicas: 1
  image: redis:7.0
  storage:
    size: 1Gi
    storageClassName: standard
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"