apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-operator-system

resources:
- jaeger-config.yaml

commonLabels:
  app.kubernetes.io/name: redis-operator
  app.kubernetes.io/component: tracing
  app.kubernetes.io/part-of: redis-operator

commonAnnotations:
  tracing.jaegertracing.io/version: v1